# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 942170411215.dkr.ecr.us-east-2.amazonaws.com/go-chat-app
  tag: latest
  pullPolicy: Always

imagePullSecrets: 
  name: awsecr-cred

service:
  port: 3050
  targetPort: 80

host: ae7c6d565343446b0abe4dfbf2a30192-1902897671.us-east-2.elb.amazonaws.com


resources: 
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

readinessProbe: 
  periodSeconds: 5
  initialDelaySeconds: 5
  failureThreshold: 3 
  httpGet:
    path: /
    port: 80

livenessProbe: 
  periodSeconds: 5
  initialDelaySeconds: 5
  failureThreshold: 3 
  httpGet:
    path: /
    port: 80

horizontalPodAutoscaler: 
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 95
