{{- if .Values.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "api.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "api.name" . }}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
{{- end }}