apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "ingress-ws"
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api(/|$)(.*) # removing /api/ 
            backend:
              serviceName: {{ include "api.fullname" . }}
              servicePort: {{ .Values.service.port }}