# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 942170411215.dkr.ecr.us-east-2.amazonaws.com/go-chat-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: 
  name: awsecr-cred

service:
  port: 3051
  targetPort: 80
  nodePort: 31516


resources: 
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

readinessProbe: 
  periodSeconds: 5
  initialDelaySeconds: 5
  failureThreshold: 3 
  httpGet:
    path: /health
    port: 80

livenessProbe: 
  periodSeconds: 5
  initialDelaySeconds: 5
  failureThreshold: 3 
  httpGet:
    path: /health
    port: 80

horizontalPodAutoscaler: 
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 95
    
